#!/usr/bin/env bash
set -euo pipefail
if [ -n "${DEBUG:+x}" ]; then
    set -x
fi

print_help() {
    printf 'usage: %s [-t TARGET] -- source...\n' "$(basename "$0")"
    printf '\nHard link source(s) to another directory.\n'
    printf '\npositional arguments:\n'
    printf '  source                source(s) to hard link\n'
    printf '\noptional arguments:\n'
    printf '  -h, --help            display this help and exit\n'
    printf '  -t TARGET, --target TARGET\n'
    printf '                        target directory for hard links\n'
    printf '  --version             output version information and exit\n'
}

print_version() {
    printf '%s\n' '2020.08.16'
}

target="${PWD}"

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            print_help
            exit
            ;;
        -t|--target)
            target="$(dirname "${2}/.")"
            shift
            ;;
        --version)
            print_version
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            printf 'ERROR: unknown option: %s\n' "$1" >&2
            print_help
            exit 1
            ;;
    esac
    shift
done

if [ $# -eq 0 ]; then
    print_help
    exit
fi

mkdir -p "${target}"

while [ $# -gt 0 ]; do
    if [ -f "$1" ]; then
        ln -t "${target}" "$1"
    else
        find "$1" -type d -not -empty -print0 \
        | while IFS= read -r -d '' sdir; do
            tdir="${target}/${sdir#$1}"
            tdir="${tdir%/}"
            mkdir -p "${tdir}"
            find "$sdir" -maxdepth 1 -type f -print0 \
            | xargs -r0 ln -t "${tdir}"
        done
    fi
    shift
done
